Add optional thresholds support to Namesake CLI #1
nalmadi/Namesake pull request #7
Opened 2023-06-13 21:53 UTC by mlanicaputo

Addresses #1

This PR adds optional thresholds to the Namesake CLI. This enables users to use custom similarity thresholds when evaluating identifier similarity, in addition to supporting the previous default values.

2023-06-13 23:01 UTC, nalmadi requested changes
Great work checking for validity and updating readme to reflect changes.  I will approve this as soon as you make the suggested changes to the readme file.  Thanks @mlanicaputo!

2023-06-13 23:01 UTC, nalmadi commented on README.md
> +To run Namesake on the file test1.py with custom similarity thresholds `(0.5, 0.6 0.7)`:
Did you mean (0.5, 0.6, 0.7)?

2023-06-13 23:01 UTC, nalmadi commented on namesake.py
> +    file.close()
Good catch!

2023-06-13 23:01 UTC, nalmadi commented on README.md
> +To run Namesake on the file test1.py with custom similarity thresholds `(0.5, 0.6 0.7)`:
Also, can we add a description of the order? like: [orth_threshold] [phon_threshold] [sem_threshold]

2023-06-14 13:47 UTC, mlanicaputo commented on README.md
> +To run Namesake on the file test1.py with custom similarity thresholds `(0.5, 0.6 0.7)`:
Good call; I can include this in the usage description instead of having two different examples.

2023-06-14 16:27 UTC, merged

2023-06-14 16:28 UTC, nalmadi commented
Thanks @mlanicaputo!